# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ab6c71ea4873e195835b7420f9c9c74add51d9d568b61ccf83880aab8663834a8ad608784403ce1f8c5d7524ab04b8aeda72dea6fe55518b572258cf78686ae6

test:
  secret_key_base: c58414c565b76e4a8a33eef5db925a4b5f55e43960c98e9c6ce73db2cb4ef26c8c58cda50abd7e43993b799a1bfc4925960d5eef0c84abd61acc56cb8e331375

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
